### ISSUE TITLE
problems with common module 

### ISSUE THREAD

**Issue by Blues5** [gugarosa/LibKeras#1]
cnet = common.ConvNet()
AttributeError: 'module' object has no attribute 'ConvNet'

**Comment by gugarosa** [comment]
Could you be a little more specific whether in which environment you are running this, please?

Check if your main python file, the one that you are using the 'common.ConvNet()' line is importing the common.py package included in this repository, for example, the same as line 3 in train.py.

**Comment by Koeldc** [comment]
I'm using tensorflow inside the virtual environment

Using TensorFlow backend.
[extract_features.tar.gz](https://github.com/gugarosa/LibKeras/files/1294120/extract_features.tar.gz)


Traceback (most recent call last):
  File "extract_features.py", line 21, in <module>
    cnet = common.ConvNet()
AttributeError: 'module' object has no attribute 'ConvNet'


only thing I've changed in the sample/extract_features.py file is the default directory path-->


# Default directory
root_out = "/home/koeldc23/target/images/expt/"

**Comment by gugarosa** [comment]
That's odd, I've just tested and everything seems to be ok. Do the following, if possible, please:

1. Re-clone the entire repository;
2. Follow these instructions: https://github.com/gugarosa/LibKeras/wiki/Installation (Basically add a new environment variable and point your default folder on common.py)
3. Try running again from the default folder 'python examples/imagenet/extract_features.py -i ...'

It seems to me that it is a missing reference problem, where your current python script cannot find its previous import, maybe because it's in a different folder or something else.
